brokerAddress: broker.hivemq.com:1883
clientID: matrix-notification-matrix-agent
animationTopic: nguyenvanduocit/feeds/matrix-notification.animation
idleAnimationTopic: nguyenvanduocit/feeds/matrix-notification.idle-animation
