/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2 */

#ifndef PB_ANIMATION_PB_H_INCLUDED
#define PB_ANIMATION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _AnimationID {
    AnimationID_SUCCESS = 0,
    AnimationID_ERROR = 1,
    AnimationID_LOADING = 2,
    AnimationID_STROBE = 3,
    AnimationID_CYLON_BOUNCE = 4,
    AnimationID_SPARKLE = 5
} AnimationID;

/* Struct definitions */
typedef struct _AnimationArg {
    int32_t duration;
    AnimationID animation_id;
} AnimationArg;


/* Helper constants for enums */
#define _AnimationID_MIN AnimationID_SUCCESS
#define _AnimationID_MAX AnimationID_SPARKLE
#define _AnimationID_ARRAYSIZE ((AnimationID)(AnimationID_SPARKLE+1))


/* Initializer values for message structs */
#define AnimationArg_init_default                {0, _AnimationID_MIN}
#define AnimationArg_init_zero                   {0, _AnimationID_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define AnimationArg_duration_tag                1
#define AnimationArg_animation_id_tag            2

/* Struct field encoding specification for nanopb */
#define AnimationArg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    duration,          1) \
X(a, STATIC,   SINGULAR, UENUM,    animation_id,      2)
#define AnimationArg_CALLBACK NULL
#define AnimationArg_DEFAULT NULL

extern const pb_msgdesc_t AnimationArg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AnimationArg_fields &AnimationArg_msg

/* Maximum encoded size of messages (where known) */
#define AnimationArg_size                        13

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
