// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: animation.proto

package animation

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AnimationArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Duration    uint32 `protobuf:"varint,1,opt,name=duration,proto3" json:"duration,omitempty"`
	AnimationId uint32 `protobuf:"varint,2,opt,name=animation_id,json=animationId,proto3" json:"animation_id,omitempty"`
	ColorId     uint32 `protobuf:"varint,3,opt,name=color_id,json=colorId,proto3" json:"color_id,omitempty"`
	Speed       uint32 `protobuf:"varint,4,opt,name=speed,proto3" json:"speed,omitempty"`
	Brightness  uint32 `protobuf:"varint,5,opt,name=brightness,proto3" json:"brightness,omitempty"`
}

func (x *AnimationArg) Reset() {
	*x = AnimationArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_animation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnimationArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimationArg) ProtoMessage() {}

func (x *AnimationArg) ProtoReflect() protoreflect.Message {
	mi := &file_animation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimationArg.ProtoReflect.Descriptor instead.
func (*AnimationArg) Descriptor() ([]byte, []int) {
	return file_animation_proto_rawDescGZIP(), []int{0}
}

func (x *AnimationArg) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *AnimationArg) GetAnimationId() uint32 {
	if x != nil {
		return x.AnimationId
	}
	return 0
}

func (x *AnimationArg) GetColorId() uint32 {
	if x != nil {
		return x.ColorId
	}
	return 0
}

func (x *AnimationArg) GetSpeed() uint32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *AnimationArg) GetBrightness() uint32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

type IdleAnimationArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimationId uint32 `protobuf:"varint,2,opt,name=animation_id,json=animationId,proto3" json:"animation_id,omitempty"`
	ColorId     uint32 `protobuf:"varint,3,opt,name=color_id,json=colorId,proto3" json:"color_id,omitempty"`
	Speed       uint32 `protobuf:"varint,4,opt,name=speed,proto3" json:"speed,omitempty"`
	Brightness  uint32 `protobuf:"varint,5,opt,name=brightness,proto3" json:"brightness,omitempty"`
}

func (x *IdleAnimationArg) Reset() {
	*x = IdleAnimationArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_animation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdleAnimationArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdleAnimationArg) ProtoMessage() {}

func (x *IdleAnimationArg) ProtoReflect() protoreflect.Message {
	mi := &file_animation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdleAnimationArg.ProtoReflect.Descriptor instead.
func (*IdleAnimationArg) Descriptor() ([]byte, []int) {
	return file_animation_proto_rawDescGZIP(), []int{1}
}

func (x *IdleAnimationArg) GetAnimationId() uint32 {
	if x != nil {
		return x.AnimationId
	}
	return 0
}

func (x *IdleAnimationArg) GetColorId() uint32 {
	if x != nil {
		return x.ColorId
	}
	return 0
}

func (x *IdleAnimationArg) GetSpeed() uint32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *IdleAnimationArg) GetBrightness() uint32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

var File_animation_proto protoreflect.FileDescriptor

var file_animation_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x9e, 0x01, 0x0a, 0x0c, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41,
	0x72, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21,
	0x0a, 0x0c, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x70, 0x65,
	0x65, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65,
	0x73, 0x73, 0x22, 0x86, 0x01, 0x0a, 0x10, 0x49, 0x64, 0x6c, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x41, 0x72, 0x67, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x6e, 0x69, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x61,
	0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x62,
	0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0a, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x42, 0x0d, 0x5a, 0x0b, 0x2e,
	0x3b, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_animation_proto_rawDescOnce sync.Once
	file_animation_proto_rawDescData = file_animation_proto_rawDesc
)

func file_animation_proto_rawDescGZIP() []byte {
	file_animation_proto_rawDescOnce.Do(func() {
		file_animation_proto_rawDescData = protoimpl.X.CompressGZIP(file_animation_proto_rawDescData)
	})
	return file_animation_proto_rawDescData
}

var file_animation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_animation_proto_goTypes = []interface{}{
	(*AnimationArg)(nil),     // 0: AnimationArg
	(*IdleAnimationArg)(nil), // 1: IdleAnimationArg
}
var file_animation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_animation_proto_init() }
func file_animation_proto_init() {
	if File_animation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_animation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnimationArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_animation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdleAnimationArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_animation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_animation_proto_goTypes,
		DependencyIndexes: file_animation_proto_depIdxs,
		MessageInfos:      file_animation_proto_msgTypes,
	}.Build()
	File_animation_proto = out.File
	file_animation_proto_rawDesc = nil
	file_animation_proto_goTypes = nil
	file_animation_proto_depIdxs = nil
}
