/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2 */

#ifndef PB_BRIGHTNESS_PB_H_INCLUDED
#define PB_BRIGHTNESS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _SetBrightnessArg {
    uint32_t level;
} SetBrightnessArg;


/* Initializer values for message structs */
#define SetBrightnessArg_init_default            {0}
#define SetBrightnessArg_init_zero               {0}

/* Field tags (for use in manual encoding/decoding) */
#define SetBrightnessArg_level_tag               1

/* Struct field encoding specification for nanopb */
#define SetBrightnessArg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   level,             1)
#define SetBrightnessArg_CALLBACK NULL
#define SetBrightnessArg_DEFAULT NULL

extern const pb_msgdesc_t SetBrightnessArg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SetBrightnessArg_fields &SetBrightnessArg_msg

/* Maximum encoded size of messages (where known) */
#define SetBrightnessArg_size                    6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
