// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: brightness.proto

package brightness

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SetBrightnessArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level uint32 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *SetBrightnessArg) Reset() {
	*x = SetBrightnessArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brightness_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetBrightnessArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBrightnessArg) ProtoMessage() {}

func (x *SetBrightnessArg) ProtoReflect() protoreflect.Message {
	mi := &file_brightness_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBrightnessArg.ProtoReflect.Descriptor instead.
func (*SetBrightnessArg) Descriptor() ([]byte, []int) {
	return file_brightness_proto_rawDescGZIP(), []int{0}
}

func (x *SetBrightnessArg) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

var File_brightness_proto protoreflect.FileDescriptor

var file_brightness_proto_rawDesc = []byte{
	0x0a, 0x10, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x28, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e,
	0x65, 0x73, 0x73, 0x41, 0x72, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x42, 0x0e, 0x5a, 0x0c,
	0x2e, 0x3b, 0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_brightness_proto_rawDescOnce sync.Once
	file_brightness_proto_rawDescData = file_brightness_proto_rawDesc
)

func file_brightness_proto_rawDescGZIP() []byte {
	file_brightness_proto_rawDescOnce.Do(func() {
		file_brightness_proto_rawDescData = protoimpl.X.CompressGZIP(file_brightness_proto_rawDescData)
	})
	return file_brightness_proto_rawDescData
}

var file_brightness_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_brightness_proto_goTypes = []interface{}{
	(*SetBrightnessArg)(nil), // 0: SetBrightnessArg
}
var file_brightness_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_brightness_proto_init() }
func file_brightness_proto_init() {
	if File_brightness_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_brightness_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetBrightnessArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_brightness_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_brightness_proto_goTypes,
		DependencyIndexes: file_brightness_proto_depIdxs,
		MessageInfos:      file_brightness_proto_msgTypes,
	}.Build()
	File_brightness_proto = out.File
	file_brightness_proto_rawDesc = nil
	file_brightness_proto_goTypes = nil
	file_brightness_proto_depIdxs = nil
}
